# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T08:16:51+00:00



import argparse
import json
import os
from datetime import datetime
from typing import *

from autogen.mcp.mcp_proxy import MCPProxy
from autogen.mcp.mcp_proxy.security import BaseSecurity

from models import AnnunciatorMessageType, MessageViewModel

app = MCPProxy(
    contact={
        'email': 'softwareengineering@parliament.uk',
        'name': 'UK Parliament',
        'url': 'https://www.parliament.uk/',
    },
    description='Get data from the annunciator system.',
    title='Annunciator content API',
    version='v1',
)


@app.get(
    '/api/Message/message/{annunciator}/current',
    tags=['message_annunciator_management'],
)
def get_api__message_message__annunciator_current(annunciator: AnnunciatorMessageType):
    """
    Return the current message by annunciator type
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/api/Message/message/{annunciator}/{date}', tags=['message_annunciator_management']
)
def get_api__message_message__annunciator__date(
    annunciator: AnnunciatorMessageType, date: datetime = ...
):
    """
    Return the most recent message by annunciator after date time specified
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="MCP Server")
    parser.add_argument(
        "transport",
        choices=["stdio", "sse", "streamable-http"],
        help="Transport mode (stdio, sse or streamable-http)",
    )
    args = parser.parse_args()

    if "CONFIG_PATH" in os.environ:
        config_path = os.environ["CONFIG_PATH"]
        app.load_configuration(config_path)

    if "CONFIG" in os.environ:
        config = os.environ["CONFIG"]
        app.load_configuration_from_string(config)

    if "SECURITY" in os.environ:
        security_params = BaseSecurity.parse_security_parameters_from_env(
            os.environ,
        )

        app.set_security_params(security_params)

    mcp_settings = json.loads(os.environ.get("MCP_SETTINGS", "{}"))

    app.get_mcp(**mcp_settings).run(transport=args.transport)
