# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T08:16:51+00:00

from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import List, Optional

from pydantic import BaseModel, ConfigDict


class AnnunciatorMessageType(Enum):
    CommonsMain = 'CommonsMain'
    LordsMain = 'LordsMain'


class ContentStyle(Enum):
    DividerSolid = 'DividerSolid'
    EmptyLine = 'EmptyLine'
    Member = 'Member'
    Footer = 'Footer'
    AnsweringBody = 'AnsweringBody'
    WestminsterHallInfo = 'WestminsterHallInfo'
    GrandCommitteeInfo = 'GrandCommitteeInfo'
    DividerDotted = 'DividerDotted'
    DividerDashed = 'DividerDashed'
    Division = 'Division'
    Text150 = 'Text150'
    Text140 = 'Text140'
    Text130 = 'Text130'
    Text120 = 'Text120'
    Text110 = 'Text110'
    Text100 = 'Text100'
    Text90 = 'Text90'
    Text80 = 'Text80'
    Text70 = 'Text70'


class ContentType(Enum):
    Generic = 'Generic'
    Member = 'Member'
    OralQuestionTime = 'OralQuestionTime'
    AnsweringBody = 'AnsweringBody'
    Bill = 'Bill'


class HorizontalAlignment(Enum):
    Left = 'Left'
    Right = 'Right'
    Centre = 'Centre'


class HouseMembershipViewModel(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    membershipFrom: Optional[str] = None


class PartyViewModel(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    backgroundColour: Optional[str] = None
    id: Optional[int] = None
    name: Optional[str] = None


class ScrollingMessageAlertType(Enum):
    Standard = 'Standard'
    SecondaryChamber = 'SecondaryChamber'
    Alert = 'Alert'
    SecurityNormal = 'SecurityNormal'
    SecurityHigh = 'SecurityHigh'


class SlideType(Enum):
    Debate = 'Debate'
    Division = 'Division'
    OralQuestionTime = 'OralQuestionTime'
    UrgentQuestion = 'UrgentQuestion'
    Statement = 'Statement'
    Prayers = 'Prayers'
    HouseRisen = 'HouseRisen'
    Generic = 'Generic'
    NotSitting = 'NotSitting'
    PrimeMinistersQuestions = 'PrimeMinistersQuestions'
    PointsOfOrder = 'PointsOfOrder'
    BlankSlide = 'BlankSlide'


class Sounds(Enum):
    NewSlide = 'NewSlide'
    DivisionBell = 'DivisionBell'
    Alert = 'Alert'
    GenericBeep = 'GenericBeep'


class VerticalAlignment(Enum):
    Top = 'Top'
    Middle = 'Middle'
    Bottom = 'Bottom'


class MemberViewModel(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: Optional[int] = None
    latestHouseMembership: Optional[HouseMembershipViewModel] = None
    latestParty: Optional[PartyViewModel] = None
    nameAddressAs: Optional[str] = None
    nameDisplayAs: Optional[str] = None
    nameFullTitle: Optional[str] = None
    nameListAs: Optional[str] = None
    thumbnailUrl: Optional[str] = None


class ScrollingMessageViewModel(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    alertType: Optional[ScrollingMessageAlertType] = None
    content: Optional[str] = None
    displayFrom: Optional[datetime] = None
    displayTo: Optional[datetime] = None
    id: Optional[int] = None
    verticalAlignment: Optional[VerticalAlignment] = None


class LineViewModel(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    content: Optional[str] = None
    contentAdditionalJson: Optional[str] = None
    contentType: Optional[ContentType] = None
    contentUrl: Optional[str] = None
    displayOrder: Optional[int] = None
    forceCapitalisation: Optional[bool] = None
    horizontalAlignment: Optional[HorizontalAlignment] = None
    member: Optional[MemberViewModel] = None
    style: Optional[ContentStyle] = None
    verticalAlignment: Optional[VerticalAlignment] = None


class SlideViewModel(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    carouselDisplaySeconds: Optional[int] = None
    carouselOrder: Optional[int] = None
    id: Optional[int] = None
    lines: Optional[List[LineViewModel]] = None
    slideTime: Optional[datetime] = None
    soundToPlay: Optional[Sounds] = None
    speakerTime: Optional[datetime] = None
    type: Optional[SlideType] = None


class MessageViewModel(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    annunciatorDisabled: Optional[bool] = None
    annunciatorType: Optional[AnnunciatorMessageType] = None
    id: Optional[int] = None
    isSecurityOverride: Optional[bool] = None
    publishTime: Optional[datetime] = None
    scrollingMessages: Optional[List[ScrollingMessageViewModel]] = None
    showCommonsBell: Optional[bool] = None
    showLordsBell: Optional[bool] = None
    slides: Optional[List[SlideViewModel]] = None
